spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:PlayZone
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: support.playzone@hotmail.com
    password: PlayZone$2023
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8000

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://192.168.110.25:5432/PlayZone
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: support.playzone@hotmail.com
    password: PlayZone$2023
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8000
  address: 0.0.0.0
