spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:Test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: false
springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
server:
  port: 8000
app:
  data-init: true
  http-host: http://localhost:4200